### PR TITLE
Avoid encoding mismatch issue with PgSQL

### PR DESCRIPTION
**Pull request by danielkza**

### CODE REVIEW

**Comment by rafamanzo** [comment]
Why `template0` instead of `template1` (the default one)? The encoding is not something that should be addressed by the DBMS?

Going further, if you really want to address this at client side why not using the correct configuration to this end `encoding`? (Have a look at http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/PostgreSQLAdapter.html)

**Comment by danielkza** [comment]
Omitting the template key is the same as using template1. The problem
happens when template1 is not UTF-8. The table creation fails with an
encoding mismatch. Using template0 just ignores the default encoding to
always use our choice, which is already UTF-8.

Em qui, 25 de fev de 2016 08:12, Rafael Reggiani Manzo <
notifications@github.com> escreveu:

**Comment by rafamanzo** [comment]
`template0` is only UTF-8 if the you are lucky that PostgreSQL has been installed that way. It's not something you can assume true on all systems. Suppose a bizarre Windows PostgreSQL server ;)

And I repeat the second question:

"Going further, if you really want to address this at client side why not using the correct configuration to this end encoding? (Have a look at http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/PostgreSQLAdapter.html)"

**Comment by danielkza** [comment]
template0 means ignoring the encoding set by default on the server. template**1** is the one that may not be UTF-8 and that we were having problems with.

And changing the encoding doesn't matter. The encoding is already correctly set to UTF-8. The issue is that the *server* default encoding is ASCII and it refuses creating an UTF-8 table *unless* you use template0.

**Pull request merged**
