### PR TITLE
Fixed range method on metric result for infinite ranges

### PR DESCRIPTION
**Pull request by marcheing**
Using the branch (kalibro_range_range) with the fix in kalibro client

Signed off by: Daniel Miranda <danielkza2@gmail.com>

See mezuro/kalibro_client#72

### CODE REVIEW

**Comment by diegoamc** [comment]
Maybe we should reference the related PRs on the description. What do you think?

**Comment by danielkza** [comment]
Updated, thanks!

**Comment by rafamanzo** [comment]
What do you think about waiting for a kalibro_client release? So we don't have to open a new PR before the release.

**Comment by danielkza** [comment]
We can wait until the kalibro_cliient PR gets in, sure.

**Pull request merged**
