### PR TITLE
Gemfile: change kalibro_client dependency to use the Git repository

### PR DESCRIPTION
**Pull request by danielkza**
Change the kalibro_client dependency from a version number to our Git
repository, pointed at the stable branch. This allows a developer to
override it with their local copy by running

bundle config local.kalibro_client /path/to/kalibro_client

Bundle forces you to match branches even on local copies by default. To
disable that and make any local branch acceptable run

bundle config disable_local_branch_check true

### CODE REVIEW

**Comment by rafamanzo** [comment]
Why you want to add this? Replacing whenever necessary is not enough?

Keeping the gem file is more user-friendly for new developers or users that just want to install and make minor changes.

**Comment by danielkza** [comment]
> Why you want to add this? Replacing whenever necessary is not enough?

Bundle only supports overrides for Git dependencies, and not being able to locally work on a copy of kalibro_client and have it be used for the other services is confusing and annoying. For example, kalibro_client's acceptance tests talk to kalibro_processor, which won't even be using the same code you're trying to test, but actually whatever version is up on RubyGems.

> Keeping the gem file is more user-friendly for new developers or users that just want to install and make minor changes.

What makes the repository less user-friendly? The checkout process is the same and bundle install will clone for you if you don't have a local override. We already have at least one Git dependency on Prezento and it hasn't caused any problems so far.

**Comment by danielkza** [comment]
Well I just found a con of using the repository: the Gemfile.lock will point to a local commit, and break if it isn't merged. That's probably the reason for the branch restriction by default.

We should probably wait to discuss a bit more, next time we meet, before choosing whether to do it or not.

**Comment by rafamanzo** [comment]
Actually on your development environment whenever you need you can use the `path` on Gemfile and work and test any modified version. Have a look at: http://bundler.io/v1.9/gemfile.html

Don't you think that for development this is even better than pointing to a git commit reference since it will give you more freedom to modify the gem's code?

Regarding user friendly (I mean new developers friendly), it's good that you pointed out Prezento's Gemfile because it is a good example of the confusion it causes. Looking at the blame you will find that twitter-bootstrap-rails was not pointing to the git repository since day 1. It was forced by the gem developers.  And by the gem's github issues you can see the kind of confusion among developers this generates. For example:

https://github.com/seyhunak/twitter-bootstrap-rails/issues/831
https://github.com/seyhunak/twitter-bootstrap-rails/issues/819
https://github.com/seyhunak/twitter-bootstrap-rails/pull/706

Dealing with rubygems is more intuitive for people and after seeing this I'm seriously considering to switch to https://github.com/toadkicker/railsstrap there.

Finally I was not aware of the Gemfile.lock issue. So, yes it one more reason fot doing this on the version that is considered stable and for us to change the gem on prezento.

Tomorrow we pair and close this and many other PRs :)

**Pull request closed without merging**
