### PR TITLE
Fix test that depended on previous cache state

### PR DESCRIPTION
**Pull request by diegoamc**
Instead of clearing the cache after the test, do it beforehand. That way
we ensure the test has all the environment dependencies it needs to run
correctly.

Signed-off-by: Daniel Miranda <danielkza2@gmail.com>

### CODE REVIEW

**Comment by rafamanzo** [comment]
Does this not leave the cache dirty for the following specs then? What do you think about clearing the cache just once after the context?

**Comment by rafamanzo** [comment]
Or maybe there is some new test that are missing proper mocks. I don't think this fix is correct one, just a workaround.

**Comment by diegoamc** [comment]
I don't think it's incorrect, but incomplete. Further investigation is necessary so future tests do not face the same problem.

**Comment by rafamanzo** [comment]
Replaced by: https://github.com/mezuro/kalibro_processor/pull/178

**Pull request closed without merging**
